### Question 00
import necessary libraries in the box below

In [2]:
import numpy as np

### Question 01
Create a NumPy array from [1,2,3, ..., 12].

In [3]:
array_01 = np.arange(1,13)
array_01

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Question 02
Print the type of array array_01

In [4]:
print(type(array_01))

<class 'numpy.ndarray'>


### Question 03
Reshape array_01 into 3 x 4 matrix.

In [5]:
array_03 = array_01.reshape(3,4)
array_03

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Question 04
Get the length of the array_03.

In [6]:
print(array_03.size)

12


### Question 05
Print the second element of the second row in array_03.

In [7]:
print(array_03[1,1])

6


### Question 06
Multiply all elements of array_03 by 2.

In [8]:
array_06 = array_03*2
array_06

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### Question 07
Add 5 to all elements of array_06.

In [9]:
print(array_06+5)

[[ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


### Question 07
Create an array of 18 zeros.

In [10]:
array_07 = np.zeros(18)
array_07

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

### Question 08
Create an array of 20 fours.

In [11]:
array_08 = np.ones(20) * 4
array_08

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4.])

### Question 09
Create numbers from 0 to 20.

In [12]:
array_09 = np.arange(21)
array_09

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### Question 10
Create 24 random numbers between 0 and 1.
Then, Reshape it into matrix with 6 rows.

In [13]:
array_10 = np.random.random(24)
array_10 = array_10.reshape(6,4)
array_10

array([[0.30874994, 0.26349166, 0.18972394, 0.17142946],
       [0.74419227, 0.68081734, 0.53016261, 0.11257101],
       [0.96209882, 0.61617063, 0.47183607, 0.45727299],
       [0.84230439, 0.47813154, 0.21528058, 0.70590532],
       [0.42534542, 0.65208112, 0.10000055, 0.71560622],
       [0.0684969 , 0.88676467, 0.1510785 , 0.81652492]])

### Question 11
Convert array_08 to String type.

In [14]:
array_11 = array_08.astype(str)
array_11

array(['4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0'], dtype='<U32')

### Question 12
Find sum of all rows in array_11

In [15]:
array_12 = array_11.astype(float).reshape(4,5)
print(array_12.sum(axis= 0))

[16. 16. 16. 16. 16.]


### Question 13
Find mean of elements of array_10 'in' each row.

In [16]:
array_14 = array_10

print(array_14.mean(axis =0))

[0.55853129 0.59624283 0.27634704 0.49655165]


### Question 14
Reverse the array_10.

In [17]:
print(array_10[::-1])

[[0.0684969  0.88676467 0.1510785  0.81652492]
 [0.42534542 0.65208112 0.10000055 0.71560622]
 [0.84230439 0.47813154 0.21528058 0.70590532]
 [0.96209882 0.61617063 0.47183607 0.45727299]
 [0.74419227 0.68081734 0.53016261 0.11257101]
 [0.30874994 0.26349166 0.18972394 0.17142946]]


### Question 15
Add array [1,2,3,4,5,6] to array_10.

In [26]:
array_15 = np.append([1,2,3,4,5,6],array_10)
print(array_15)

[1.         2.         3.         4.         5.         6.
 0.30874994 0.26349166 0.18972394 0.17142946 0.74419227 0.68081734
 0.53016261 0.11257101 0.96209882 0.61617063 0.47183607 0.45727299
 0.84230439 0.47813154 0.21528058 0.70590532 0.42534542 0.65208112
 0.10000055 0.71560622 0.0684969  0.88676467 0.1510785  0.81652492]


### Question 16
Print odd column of array_10

In [25]:
print(array_10[:,2])

[0.18972394 0.53016261 0.47183607 0.21528058 0.10000055 0.1510785 ]


### Question 17
Create 3x3 zeros matrix.

In [28]:
array_17 = np.zeros((3,3))
array_17

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Question 18
Sort the array_10.

In [29]:
print(np.sort(array_10))

[[0.17142946 0.18972394 0.26349166 0.30874994]
 [0.11257101 0.53016261 0.68081734 0.74419227]
 [0.45727299 0.47183607 0.61617063 0.96209882]
 [0.21528058 0.47813154 0.70590532 0.84230439]
 [0.10000055 0.42534542 0.65208112 0.71560622]
 [0.0684969  0.1510785  0.81652492 0.88676467]]


### Question 19
Transpose the array_10 

In [30]:
print(array_10.T)

[[0.30874994 0.74419227 0.96209882 0.84230439 0.42534542 0.0684969 ]
 [0.26349166 0.68081734 0.61617063 0.47813154 0.65208112 0.88676467]
 [0.18972394 0.53016261 0.47183607 0.21528058 0.10000055 0.1510785 ]
 [0.17142946 0.11257101 0.45727299 0.70590532 0.71560622 0.81652492]]


### Question 20
Create even numbers from 11 to 56.

In [33]:
array_20 = np.arange(12,57,2)
array_20

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54, 56])